#define QSNAPSHOT_VERSION_MAJOR ${QSNAPSHOT_VERSION_MAJOR}
#define QSNAPSHOT_VERSION_MINOR ${QSNAPSHOT_VERSION_MINOR}
#define QSNAPSHOT_VERSION_PATCH ${QSNAPSHOT_VERSION_PATCH}
#define QSNAPSHOT_VERSION ${QSNAPSHOT_VERSION}

#cmakedefine01 HAVE_X11_EXTENSIONS_SHAPE_H
#cmakedefine01 HAVE_X11_EXTENSIONS_XFIXES_H

#define QSNAPSHOT_STRINGIZER(x) #x
